spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flight_system
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:60000}


# Add this logging section
logging:
  level:
    com.flightbooking.common.util.JwtUtil: DEBUG
    com.flightbooking.common.common.JwtAuthenticationFilter: DEBUG
    com.flightbooking.search.controller: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"